version: "3.9"

services:

  postgres18:
    image: postgres:17
    container_name: postgres18
    environment:
      POSTGRES_DB: shiksha-intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

  localstack:
    image: localstack/localstack:3.5
    container_name: localstack
    ports:
      - "4566:4566" # main edge port
      - "4510-4559:4510-4559" # internal services
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres-data:
  redis-data:
