package com.project.edusync.enrollment.controller;

import com.project.edusync.enrollment.service.SseEmitterRegistry;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
import jakarta.servlet.http.HttpServletResponse;

/**
 * SSE endpoint that the frontend subscribes to BEFORE triggering a bulk import.
 *
 * <p><b>Usage flow:</b></p>
 * <ol>
 *   <li>Frontend generates a unique {@code sessionId} (e.g. UUID v4).</li>
 *   <li>Frontend opens an EventSource to {@code GET /api/v1/bulk-import/stream/{sessionId}}.</li>
 *   <li>Frontend uploads the CSV to {@code POST /api/v1/auth/bulk-import/{userType}} with the same {@code sessionId} header.</li>
 *   <li>Backend emits {@code ROW_SUCCESS}, {@code ROW_FAILURE} per row, then {@code JOB_COMPLETE} or {@code JOB_FAILED} at the end.</li>
 * </ol>
 *
 * <p>The stream endpoint is <b>intentionally unauthenticated at the HTTP layer</b>
 * because {@code EventSource} in browsers cannot set custom headers (e.g. Bearer token).
 * The sessionId acts as a single-use opaque token — it is unguessable (UUID) and
 * is only useful for the duration of one import job.</p>
 */
@RestController
@RequestMapping("${api.url}/bulk-import/stream")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Bulk Import", description = "CSV bulk import endpoints with real-time SSE progress")
public class BulkImportSseController {

    // SSE connection kept alive for up to 10 minutes — enough for large imports.
    private static final long SSE_TIMEOUT_MS = 10 * 60 * 1000L;

    private final SseEmitterRegistry sseEmitterRegistry;

    /**
     * Opens an SSE stream for the given import session.
     * The frontend must subscribe here BEFORE posting the CSV file.
     *
     * @param sessionId A UUID generated by the frontend that ties the SSE stream
     *                  to the subsequent CSV upload request.
     * @return A live SSE stream.
     */
    @GetMapping(value = "/{sessionId}", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @Operation(
            summary = "Subscribe to bulk import progress",
            description = "Opens a Server-Sent Events stream for real-time row-by-row progress updates " +
                          "during a bulk import job. Subscribe BEFORE posting the CSV file."
    )
    public SseEmitter streamImportProgress(
            @Parameter(description = "Unique session ID generated by the client for this import job")
            @PathVariable String sessionId,
            HttpServletResponse response) {

        response.setHeader("X-Accel-Buffering", "no");
        response.setHeader("Cache-Control", "no-cache, no-transform");

        log.info("SSE subscription received for bulk import session: {}", sessionId);
        return sseEmitterRegistry.register(sessionId, SSE_TIMEOUT_MS);
    }
}

