package com.project.edusync.enrollment.controller;

import com.project.edusync.enrollment.service.BulkImportService;
import com.project.edusync.enrollment.model.dto.BulkImportReportDTO;
import com.project.edusync.enrollment.model.dto.BulkRoomImportReportDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;

/**
 * Controller to handle bulk user registration via CSV upload.
 * This endpoint is secured and accessible only to administrative roles.
 *
 * <p>To receive real-time SSE progress updates, the client must:</p>
 * <ol>
 *   <li>Generate a unique {@code sessionId} (UUID).</li>
 *   <li>Subscribe to {@code GET /api/v1/bulk-import/stream/{sessionId}} first.</li>
 *   <li>Then post the CSV here with the {@code X-Session-Id: <sessionId>} header.</li>
 * </ol>
 * <p>If {@code X-Session-Id} is omitted, the import still runs — just without SSE updates.</p>
 */
@RestController
@AllArgsConstructor
@RequestMapping("${api.url}/auth/bulk-import")
@Tag(name = "Bulk Import", description = "CSV bulk import endpoints with real-time SSE progress")
@Slf4j
public class BulkImportController {

    private final BulkImportService bulkImportService;

    private boolean isLikelyCsv(MultipartFile file) {
        String contentType = file.getContentType() != null ? file.getContentType().toLowerCase() : "";
        String fileName = file.getOriginalFilename() != null ? file.getOriginalFilename().toLowerCase() : "";
        return contentType.contains("csv") || contentType.contains("excel") || fileName.endsWith(".csv");
    }

    /**
     * Handles the CSV file upload for bulk user registration.
     *
     * @param userType  "students" or "staff", indicating the type of users to import.
     * @param file      The multipart CSV file containing user data.
     * @param sessionId Optional. The SSE session ID from the {@code X-Session-Id} header.
     *                  When provided, real-time progress events are pushed to the open SSE stream.
     * @return A ResponseEntity containing a BulkImportReportDTO with the final results.
     */
    @PostMapping(value = "/{userType}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(
            summary = "Import users from CSV",
            description = "Upload a CSV file to bulk-import students or staff. " +
                          "Optionally provide X-Session-Id header for real-time SSE progress events.",
            security = {@SecurityRequirement(name = "bearerAuth")}
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Import processed successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid CSV or unsupported userType"),
            @ApiResponse(responseCode = "500", description = "Server error while reading import file")
    })
    public ResponseEntity<BulkImportReportDTO> handleBulkImport(
            @Parameter(description = "Target import type: students | staff", required = true)
            @PathVariable String userType,
            @Parameter(description = "CSV file containing import rows", required = true)
            @RequestParam("file") MultipartFile file,
            @Parameter(description = "Optional SSE session ID for real-time progress (generated by client)")
            @RequestHeader(value = "X-Session-Id", required = false) String sessionId) {

        log.info("[BulkImportController] Request received for userType='{}', file='{}', sessionId='{}'",
                userType, file.getOriginalFilename(), sessionId);

        if (file.isEmpty()) {
            log.warn("[BulkImportController] Rejected: uploaded file is empty for userType='{}'", userType);
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "File is empty.")
            );
        }

        if (!isLikelyCsv(file)) {
            log.warn("[BulkImportController] Rejected: non-CSV file for userType='{}', file='{}'",
                    userType, file.getOriginalFilename());
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "Invalid file type. Please upload a CSV.")
            );
        }

        try {
            BulkImportReportDTO report = bulkImportService.importUsers(file, userType, sessionId);
            log.info("[BulkImportController] Completed userType='{}' import with status='{}', successCount={}, failureCount={}",
                    userType, report.getStatus(), report.getSuccessCount(), report.getFailureCount());
            return ResponseEntity.ok(report);
        } catch (IllegalArgumentException e) {
            log.warn("[BulkImportController] Validation error for userType='{}': {}", userType, e.getMessage());
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", e.getMessage())
            );
        } catch (IOException e) {
            log.error("[BulkImportController] IO error for userType='{}': {}", userType, e.getMessage());
            return ResponseEntity.internalServerError().body(
                    new BulkImportReportDTO("FAILED", "Error processing file: " + e.getMessage())
            );
        }
    }

    @PostMapping(value = "/students-with-guardians", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(
            summary = "Import students with guardians from two CSV files",
            description = "Upload students.csv and guardians.csv together. " +
                    "Guardians are matched using studentEnrollmentNumber and phone number is used as guardian username.",
            security = {@SecurityRequirement(name = "bearerAuth")}
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Import processed successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid CSV inputs or validation failure"),
            @ApiResponse(responseCode = "500", description = "Server error while reading import files")
    })
    public ResponseEntity<BulkImportReportDTO> importStudentsWithGuardians(
            @Parameter(description = "students.csv file", required = true)
            @RequestParam("studentsFile") MultipartFile studentsFile,
            @Parameter(description = "guardians.csv file", required = true)
            @RequestParam("guardiansFile") MultipartFile guardiansFile,
            @Parameter(description = "Optional SSE session ID for real-time progress (generated by client)")
            @RequestHeader(value = "X-Session-Id", required = false) String sessionId) {

        log.info("[BulkImportController] Request received for students-with-guardians, studentsFile='{}', guardiansFile='{}', sessionId='{}'",
                studentsFile.getOriginalFilename(), guardiansFile.getOriginalFilename(), sessionId);

        if (studentsFile.isEmpty() || guardiansFile.isEmpty()) {
            log.warn("[BulkImportController] Rejected students-with-guardians import: one or both files are empty");
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "Both studentsFile and guardiansFile are required.")
            );
        }
        if (!isLikelyCsv(studentsFile) || !isLikelyCsv(guardiansFile)) {
            log.warn("[BulkImportController] Rejected students-with-guardians import: invalid file type(s)");
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "Invalid file type. Please upload CSV files.")
            );
        }

        try {
            BulkImportReportDTO report = bulkImportService.importStudentsWithGuardians(studentsFile, guardiansFile, sessionId);
            log.info("[BulkImportController] Completed students-with-guardians import with status='{}', successCount={}, failureCount={}",
                    report.getStatus(), report.getSuccessCount(), report.getFailureCount());
            return ResponseEntity.ok(report);
        } catch (IllegalArgumentException e) {
            log.warn("[BulkImportController] Validation error in students-with-guardians import: {}", e.getMessage());
            return ResponseEntity.badRequest().body(new BulkImportReportDTO("FAILED", e.getMessage()));
        } catch (IOException e) {
            log.error("[BulkImportController] IO error in students-with-guardians import: {}", e.getMessage());
            return ResponseEntity.internalServerError().body(
                    new BulkImportReportDTO("FAILED", "Error processing file: " + e.getMessage())
            );
        }
    }

    @PostMapping(value = "/rooms", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAnyAuthority('ROLE_SCHOOL_ADMIN', 'ROLE_SUPER_ADMIN')")
    @Operation(
            summary = "Import rooms from CSV",
            description = "Upload a CSV file to bulk-import rooms with optional X-Session-Id for SSE progress events.",
            security = {@SecurityRequirement(name = "bearerAuth")}
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Room import completed (success/partial/failed summary returned)"),
            @ApiResponse(responseCode = "400", description = "Invalid CSV or validation failure"),
            @ApiResponse(responseCode = "403", description = "Forbidden - requires SCHOOL_ADMIN or SUPER_ADMIN"),
            @ApiResponse(responseCode = "500", description = "Server error while reading import file")
    })
    public ResponseEntity<BulkRoomImportReportDTO> importRooms(
            @Parameter(description = "Rooms CSV file", required = true)
            @RequestParam("file") MultipartFile file,
            @Parameter(description = "Optional SSE session ID for real-time progress (generated by client)")
            @RequestHeader(value = "X-Session-Id", required = false) String sessionId) {

        log.info("[BulkImportController] Request received for rooms import, file='{}', sessionId='{}'",
                file.getOriginalFilename(), sessionId);

        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body(
                    new BulkRoomImportReportDTO("FAILED", 0, 0, 0, java.util.List.of("File is empty."))
            );
        }

        if (!isLikelyCsv(file)) {
            return ResponseEntity.badRequest().body(
                    new BulkRoomImportReportDTO("FAILED", 0, 0, 0, java.util.List.of("Invalid file type. Please upload a CSV."))
            );
        }

        try {
            return ResponseEntity.ok(bulkImportService.importRooms(file, sessionId));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(
                    new BulkRoomImportReportDTO("FAILED", 0, 0, 0, java.util.List.of(e.getMessage()))
            );
        } catch (IOException e) {
            return ResponseEntity.internalServerError().body(
                    new BulkRoomImportReportDTO("FAILED", 0, 0, 0, java.util.List.of("Error processing file: " + e.getMessage()))
            );
        }
    }
}

